### ISSUE TITLE
Some bugs

### ISSUE THREAD

**Issue by kneelian** [kspalaiologos/asmbf#117]
## Bugs with par

Instruction `par` not behaving well:

```in_ r1
mov r2, r1

par r1
out r1
```

input `101` output `0`

```in_ r1
mov r2, r1

par r2
out r2
```

input `101` output `101`

## Bugs with bitness and taperam?

Assembler error:
```
[bits 32]
stk 12
org 0

db 1

&rng_state
db 139451
```

Assembler error:
```
[bits 32]
stk 12
org 0

&red
db 31
&red_bright
db 91
```
Both give `asm2bf: reference to &red_bright (1) overflows the current bitwidth.` even after update? Cause: `[bits 32]`

**Comment by kneelian** [comment]
## Bug with sle

Calling `sle` seems to grow the stack if stack is empty:

```
stk 12
org 0

out . 
	out .a
	sle r5
	add r5, 48
	out r5
	out .a
out . 

out . 
	out .a
	sle r5
	add r5, 48
	out r5
	out .a
out . 

out . 
	out .a
	sle r5
	add r5, 48
	out r5
	out .a
out . 
```

Output: `a0a a1a a1a`. Expected probably: `a0a a0a a0a`

**Comment by kspalaiologos** [comment]
calling `dup` on an empty stack is undefined behavior. Refer to the manual.

**Comment by kspalaiologos** [comment]
sle has been fixed a while ago, thanks to Daniel.
